### Patataprint
### Configuration

# Lire la documentation en ligne :
# https://ateliers.esad-pyrenees.fr/pagetypetoprint/contenu/

# Le thème à utiliser
theme: "masterden2026"

# Le titre du document
title: L'interprétation dans les géovisualisation

# Le sous-titre éventuel du document
subtitle: "A thesis template<br class='breakprint'> in _web + print_"

# Le titre courant, si différent du titre du document
runningtitle: L'interprétation dans les géovisualisation <br class='breakprint'>_aka_ PaTaTaPrint.

# Votre nom
name: Thomas Frelet

# L’année, par ex. : 2021 – 2022
year: 2025 – 2026

# Votre diplôme, par ex. : DNA Design
diploma: Master Design

# Le mention du diplôme, par ex. : Mention Design graphique Multimédia
mention: Mémoire de recherche

# Votre pôle éventuel, par ex. : Pôle Nouveaux médias, ou
# Pôle Image, édition &amp;<br class="breakprint"> dessin de caractères
pole: Sous la direction de Nolwenn Maudet

# Le nom du fichier pdf généré depuis Chrome / Chromium
# Cf. https://ateliers.esad-pyrenees.fr/pagetypetoprint/print/
pdf: ""

# Structure du contenu (= sommaire)
parts:
  - title: Introduction
    file: content/text/0.doc0.md
    template: default

  - title: Etat de l'art
    file: content/text/1.doc1.md
    template: default

  - title: Nouvelles propositions
    file: content/text/2.doc2.md
    template: default

  - title: Résulats des tests utilisateurs
    file: content/text/3.doc3.md
    template: default

  - title: Discussion
    file: content/text/4.doc4.md
    template: default

  - title: Conclusion
    file: content/text/5.doc5.md
    template: default

  - title: Colofon
    file: content/text/6.doc6.md
    template: appendices

  - title: Annexe
    file: content/text/7.doc7.md
    template: interview

  - title: Bibliographie
    file: content/text/8.doc8.md
    template: thanks
